version: '3.9'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      cassandra:
        condition: service_healthy
      valkey:
        condition: service_started

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
      - JVM_OPTS=-Xms512m -Xmx512m  # Limit heap to 512MB
    healthcheck:
      test: ["CMD-SHELL", "cqlsh localhost -e 'SELECT cluster_name FROM system.local'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s  
  valkey:
    image: valkey/valkey:latest
    ports:
      - "6380:6379"